### ISSUE TITLE
Linkedin Logo not Visiable!

### ISSUE THREAD

**Issue by Priyanshu-official** [dibyanshu-mohanty/dibyanshu-mohanty#1]
Hey! @dibyanshu-mohanty  you Portfolio is awesome and GitHub too 

  Issue:
 - LinkedIn logo is not visible in  GitHub Dark Mod -> Readme file
 ### Make it visible with both will be awsome
![Issue](https://user-images.githubusercontent.com/55912091/118364795-95b14f00-b5b7-11eb-9198-3a0c74d5b5fa.png)

**Comment by dibyanshu-mohanty** [comment]
Yeah sure Mate . Thanks for the concern .
